# Triggers the Lumenier_build workflow in the betaflight repo
# Adding comment
name: Lumenier_workflow_dispatch

on: 
  push:

jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
      - name: Send Dispatch Event
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
            --data '{"ref": "WORKFLOW_TEST"}' \
            https://api.github.com/repos/lumenier-development/betaflight/actions/workflows/lumenier_build.yml/dispatches