# Triggers the Lumenier_build workflow in the betaflight repo

name: Lumenier_workflow_dispatch

on: 
  push:

jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
      - name: Send Dispatch Event
        run: |
          # Set wait interval (in seconds)
          wait_interval=10

          # Trigger the workflow dispatch
          response=$(curl -s -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
            --data '{"ref": "WORKFLOW_TEST"}' \
            https://api.github.com/repos/lumenier-development/betaflight/actions/workflows/lumenier_build.yml/dispatches)
          
          # Extract HTTP status code from the response
          http_status="${response: -3}"
          body="${response%${http_status}}"
          
          echo "Full response: $body"
          echo "HTTP status code: $http_status"
          
          # Check if the dispatch was successful (HTTP status 204)
          if [ "$http_status" -eq 204 ]; then
            echo "Workflow dispatch was successful."

            echo "Sleeping for $wait_interval seconds"
            sleep $wait_interval

            # Poll for the latest workflow run ID
            echo "Polling for the latest workflow run ID..."
            runs_response=$(curl -s -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
              "https://api.github.com/repos/lumenier-development/betaflight/actions/workflows/lumenier_build.yml/runs")
            
            # Extract the ID of the latest run, handle empty response
            last_run_id=$(echo $runs_response | jq -r '.workflow_runs[0].id')
            if [ "$last_run_id" != "null" ]; then
              echo "Last workflow run ID: $last_run_id"
  
              # Check the status of the latest run
              status_response=$(curl -s -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
                "https://api.github.com/repos/lumenier-development/betaflight/actions/runs/$last_run_id")
              
              status=$(echo $status_response | jq -r '.status')
              conclusion=$(echo $status_response | jq -r '.conclusion')
  
              echo "Workflow run status: $status"
              echo "Workflow run conclusion: $conclusion"
            else
              echo "No workflow run found after dispatch. Retrying..."
              exit 1  # Or add retries/polling here
            fi
          else
            echo "Error triggering workflow: $body"
            exit 1
          fi
